These should ideally be integrated into one function, but for now they're broken up in an ugly fashion:

### Final value function:

In [2]:
# this is probably inefficient, but I'm not sure whether mere 
# variable assignment is better
def get_final_values(A, B):
    """
    inputs:
    """
    for arrays in A, B:
        print(arrays)
        x = np.stack(A)
        y = np.stack(B)
        
        # get the final values from A
        A_final_val = []
        A_final_val.append(x[:,-1])
        
        # get the final values from B
        B_final_val = []
        B_final_val.append(y[:,-1])

        return A_final_val, B_final_val

### Scan function:

In [39]:
def scan(final_vals, conditions): 
    """
    inputs: 
    """
    #fv = np.asarray(final_vals)
    #fv = fv.ravel()
    cond = np.asarray(conditions)
    cond = cond.ravel()
    #print(cond)
    #print(fv)
    
    for arrays in conditions:
        for values in arrays:
            a = distance(final_vals, conditions)
    return a

### Min Function:

#### Test: 

In [61]:
import numpy as np
import copy

a = np.random.rand(10)
b = np.random.rand(10)
c = np.random.rand(10)
d = np.random.rand(10)
e = np.random.rand(10)
f = np.random.rand(10)
Data = [[a, b, c], [d, e, f]]

C1 = Data[0]
C2 = Data[1]

[array([0.25378713, 0.8838425 , 0.87709244, 0.38746759, 0.40731415,
       0.83047483, 0.98426859, 0.89431814, 0.63963662, 0.17901074]), array([0.36932281, 0.54934021, 0.26629188, 0.53763719, 0.45891232,
       0.32617194, 0.00423877, 0.18194479, 0.18629896, 0.76150412]), array([0.84408457, 0.64249812, 0.20162088, 0.49796732, 0.73071806,
       0.56747473, 0.14172309, 0.78600274, 0.54934036, 0.79591124])]


In [33]:
# because there are three arrays in each condition, this gives three values
fv = get_final_values(C1, C2)
print("Condition 1 final values:", fv[0])
print("Condition 2 final values:", fv[1])

[array([0.09265311, 0.94194784, 0.68215597, 0.44654426, 0.96186802,
       0.81161218, 0.60502895, 0.91155751, 0.27280867, 0.98776403]), array([0.64923302, 0.85939804, 0.49484797, 0.96570149, 0.98232028,
       0.86780218, 0.56037237, 0.69536066, 0.48736106, 0.03080513]), array([0.02984215, 0.54132732, 0.54067115, 0.48482013, 0.68381458,
       0.04637837, 0.00558555, 0.25766998, 0.17059131, 0.62581122])]
Condition 1 final values: [array([0.98776403, 0.03080513, 0.62581122])]
Condition 2 final values: [array([0.00464532, 0.30240498, 0.28558224])]


In [77]:
# perform scan with dummy distance function:
def distance(x, y):
    x = np.asarray(x)
    y = np.asarray(y)
    return x - y

# take the condition 1 final values and turn multidim array into 1D
fv = np.asarray(fv[0])
fv = fv.ravel()

# here's where I get into trouble:
# I have to reshape the conditions that will be scanned by hand. 
C2 = np.asarray(C2)
C2 = C2.reshape(10, 3)

# hold fixed the condition 1 final values and evaluate the distance between 
# it and condition two
dist_values = scan(fv, C2)
print(dist_values, "\n")

dist_values = dist_values.reshape(3, 10)
print(dist_values)

[[0.7339769  0.10392153 0.11067159]
 [0.60029645 0.58044988 0.1572892 ]
 [0.00349544 0.09344589 0.34812742]
 [0.8087533  0.61844122 0.43842382]
 [0.72147215 0.45012685 0.52885171]
 [0.6615921  0.98352527 0.80581924]
 [0.80146507 0.22625991 0.14367947]
 [0.34526591 0.78614316 0.48979671]
 [0.25704597 0.4202893  0.84604095]
 [0.20176129 0.43842367 0.19185279]] 

[[0.7339769  0.10392153 0.11067159 0.60029645 0.58044988 0.1572892
  0.00349544 0.09344589 0.34812742 0.8087533 ]
 [0.61844122 0.43842382 0.72147215 0.45012685 0.52885171 0.6615921
  0.98352527 0.80581924 0.80146507 0.22625991]
 [0.14367947 0.34526591 0.78614316 0.48979671 0.25704597 0.4202893
  0.84604095 0.20176129 0.43842367 0.19185279]]
